#ifndef QR_CONSTANTS_H
#define QR_CONSTANTS_H

#define REQUEST_CHALLENGE		0x01
#define REQUEST_HEARTBEAT		0x03
#define REQUEST_KEEPALIVE		0x08
#define REQUEST_AVAILABLE		0x09

#define RESPONSE_MAGIC_1		0xFE
#define RESPONSE_MAGIC_2		0xFD

#define RESPONSE_HEARTBEAT		0x01
#define RESPONSE_AVAILABLE		0x09
#define RESPONSE_KEEPALIVE		0x08
#define RESPONSE_CHALLENGE		0x0A

#endif // QR_CONSTANTS_H
